### ISSUE TITLE
Could you provide binaries for older Windows?

### ISSUE THREAD

**Issue by 1997tn** [kitepad/n4d#1]
Do you think limiting to just Windows 11 is too extreme? I downloaded your Win11 binary but it doesn't run on my computer. There is no message printed on the screen about why it failed to run, it just silently exit.

**Comment by kitepad** [comment]
If you want run on older windows version, you can pull source and build binary in your computer, and you need download vs studio 2022 community version. I'm sorry, I only build win11 edition ony my win11 box.
